# Generated by Django 3.2.6 on 2021-08-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opgave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('uitleg', models.TextField()),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('onderwerp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oefening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwoorden', models.IntegerField()),
                ('oef_datum', models.DateTimeField(verbose_name='datum gemaakt')),
                ('opgave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oef.opgave')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
