# Generated by Django 3.2.6 on 2021-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reeks',
            options={'verbose_name': 'Reeks', 'verbose_name_plural': 'Reeksen'},
        ),
        migrations.AddField(
            model_name='reeks',
            name='glob_moeilkhgr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
