# Generated by Django 3.2.6 on 2021-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb4', '0003_opgave_moeilkhgr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oefening',
            options={'verbose_name': 'Oefening', 'verbose_name_plural': 'Oefeningen'},
        ),
        migrations.AlterModelOptions(
            name='opgave',
            options={'verbose_name': 'Opgave', 'verbose_name_plural': 'Opgaven'},
        ),
        migrations.AlterField(
            model_name='reeks',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
