# Generated by Django 3.2.6 on 2021-08-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb4', '0004_auto_20210816_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='opg_titel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reeks',
            name='vereiste_level',
            field=models.CharField(default='MB1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oefening',
            name='antwoord',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='opgave',
            name='opg_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='opgave',
            name='opl_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reeks',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
