# Generated by Django 3.2.6 on 2021-08-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb4', '0005_auto_20210817_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oefening',
            name='oef_datum',
            field=models.DateTimeField(verbose_name='datum_gemaakt'),
        ),
    ]
